### ISSUE TITLE
Enhance existing webviews

### ISSUE THREAD

**Issue by alcinnz** [bleakgrey/liberate#1]
In order to most easily integrate this into Odysseus, I'd want to be able to make a call to add a Reader Mode to an existing webview. Then it can be moved outside of the core code.

If this isn't an easy refactor to do on the Liberate side, I'm willing at other options.

**Comment by cassidyjames** [comment]
It looks like Firefox and Safari both use a sort of left-aligned text icon. Firefox's is inside of a rounded rectangle, but otherwise they're pretty similar to the elementary `format-justify-left-symbolic` icon (or `format-justify-right-symbolic` in RTL languages).

**Comment by cassidyjames** [comment]
## Firefox

![Firefox-reader-view](https://user-images.githubusercontent.com/611168/57977546-fa7d4300-79b7-11e9-8d5c-aae9ca56319a.png)


## Safari

![image](https://user-images.githubusercontent.com/611168/57977543-e46f8280-79b7-11e9-8448-65552124d4f8.png)

**Comment by alcinnz** [comment]
Ah, thanks! I was searching by semantic name.

Though I do find that IconMonstr (symbolic) icon is fitting in nicely, and communicates the concept better to me.

**Comment by cassidyjames** [comment]
@alcinnz yeah semantic could be best probably, but I was just sharing some glyphs that could also work. I can also see if @danrabbit wants to add a semantic icon into the standard elementary set.
